### ISSUE TITLE
Remove configurations from version control

### ISSUE THREAD

**Issue by get-data-** [rjsears/GardenPi#1]
You should remove your secrets from version control so that you don't accidentally expose private information or allow others to access your resources through your credentials.

https://github.com/rjsears/GardenPi/blob/8e82107f259ee48cdceb6b8016380b26c4895f63/GardenPi/__init__.py#L20
https://github.com/rjsears/GardenPi/blob/8e82107f259ee48cdceb6b8016380b26c4895f63/GardenPi/__init__.py#L25

Add a `.gitignore` and reference your configuration file so it will not be tracked moving forward

**Comment by rjsears** [comment]
These are bogus already!
